# CobbleHorizons default options
defaultDifficulty = "NORMAL"
defaultResourcePacks = [ "file/Cobblemon Interface v1.6.0.zip", "file/Cobblemon Interface Modded v1.9.4.zip", "file/Battle Tracks v1.2.zip", "file/CobbleHorizons.zip", "cobbreeding:pasturefix" ]
lockDifficulty = false
