# CobbleHorizons default options
defaultDifficulty = "NORMAL"
defaultResourcePacks = [ "file/CobbleHorizons-Branding.zip", "file/Battle Tracks v1.2.zip", "cobbreeding:pasturefix" ]
lockDifficulty = false
