#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 18 22:50:46 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=ComplementaryReimagined_r5.8.1.zip
